version: "3"
services:
  web:
    image: web
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports: 
      - "5000:5000"
      - "8010:8010"
    restart: always
  redis:
    image: "redis:alpine"
    container_name: redis

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus:/etc/prometheus"
    restart: always
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  
  grafana:
    ports:
      - '3000:3000'
    environment:
      - 'GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource'
    container_name: grafana
    image: grafana/grafana