version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    image: "project"
    ports: 
      - "5000:5000"
  redis:
    image: "redis:alpine"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus:/etc/prometheus"
    restart: always
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml